### ISSUE TITLE
AR potentially not closing DB connections on reload

### ISSUE THREAD

**Issue by rendezvousIY** [Armarr/Autorank-2#229]
I'm running AutoRank on a small network of 7 servers and had scheduled /ar reload every 10 minutes to try to alleviate some sync issues. (Probably not the best option, but that's a matter for another issue)
After some time my MySQL server stopped accepting new connections, complaining about maximum connections (ERROR 1040 (HY000): Too many connections) 

I have since removed the scheduled reloads and the issue hasn't come up again which leads me to believe that AR is just creating new connections on load/reload and never closing them.

**Comment by Staartvin** [comment]
Oh god, be careful with the reload command. It is not meant to be used so regularly. It shouldn't really be used ever. One of the reasons you're getting the mysql 'maximum connections' error is due to the reloading. 

I'm not sure what syncing issues you're running into, but we should fix them. What are they exactly?

**Comment by aximilation** [comment]
Yeah, that was my thought, not using it anymore, about to post a second issue regarding the sync/time losses.

**Comment by Staartvin** [comment]
It's a good thing that you brought this to light though, as a developer you can't test everything on you're own.

**Comment by Staartvin** [comment]
Closed due to inactivity.
