### ISSUE TITLE
stats...

### ISSUE THREAD

**Issue by PandemicRuler** [Armarr/Autorank-2#305]
Stats by lolmewn refuses to work for me. I wrote a ticket several days ago and he has not responded yet. So that one is out of the question. I have tried several different statistics plugins, including Statistics, MineStats, Simple stats, PvP Stats, BeardStat and others. Is there any statistics plugin besides Stats that works with this? I only need something that counts pvp kills, and yet whenever I install a statistics plugin Autorank doesn't recognise it. Can you recommend me ANY stats plugin that works with 1.9, or even 1.8, i would be willing to downgrade? Without that i will not be able to use autorank.

**Comment by Staartvin** [comment]
At the moment, there is no other Stats plugin that is compatible with Autorank besides Stats (lolmewn). Maybe I can help you setup the Stats plugin?

**Comment by PandemicRuler** [comment]
I finally made it work by downgrading everything to 1.8. Everything seems to work well, it's just that i would rather have a 1.9 server. Is there any way to make stats work for 1.9?

**Comment by GanimanSwift** [comment]
I have found the source for stats on bitbucket and built it against spigot 1.9.  It throws an exception when I start up my server, but still creates mysql tables and appears to be working in some fashion.  However, Autorank gives me the following:

[20:32:42 INFO]: [Autorank] Could not find Stats because it's probably disabled! Does Stats properly connect to your MySQL database?
[20:32:42 INFO]: [Autorank] Found Stats plugin: Stats (by Lolmewn)
[20:32:42 INFO]: [Autorank] Stats (by Lolmewn) is not enabled!
[20:32:42 INFO]: [Autorank] Couldn't hook into Stats! Make sure the version is correct and Stats properly connects to your MySQL database.

The tables for Autorank and Stats are in the same mysql database, but for some reason Autorank doesn't see them?  Or maybe it's hooking in to something else?  Can you provide any help?

**Comment by Staartvin** [comment]
Could you turn on debugging an restart your server? Then provide the server log, please!

**Comment by GanimanSwift** [comment]
@Staartvin I realized I pulled an old branch from the Stats bitbucket repo.  I pulled their 3.0 branch instead of their "master", built against spigot 1.9 and it's all working now.  Sorry about that, I should have been checking versions.  Your plugin was even telling me "Make sure the version is correct".

**Comment by Staartvin** [comment]
No problemo. I already thought that was the problem. Does Autorank properly work on 1.9? I haven't tested it yet.

**Comment by GanimanSwift** [comment]
So far I have no issues with Autorank on 1.9.  After getting Stats working, everything seems to be working properly.  I am using an AdvancedConfig with things like kill requirements to rank up and those are now working too after building Stats against Spigot 1.9.  I have not used it before 1.9, so I can't say if anything else might not be working as expected, but I think everything is good.  Thanks for the plugin, I love it.

**Comment by Staartvin** [comment]
Good to hear everything is solid! I'll close this thread, but if you need any further assistance, don't hesitate to ask!
